
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'FA489A36B6A4D50BE59879A38F4FA4B3'
    
_lr_action_items = {'TITLE':([0,],[2,]),'TEXT':([9,47,59,],[13,13,13,]),'DESTINATION':([9,47,59,],[14,14,14,]),'RP':([53,],[58,]),'WIDTH':([9,47,59,],[15,15,15,]),'LINK':([9,47,59,],[16,16,16,]),'LINKATTR':([9,47,59,],[30,30,30,]),'FONT':([9,47,59,],[18,18,18,]),'CONSTANTVALUE':([46,],[54,]),'LB':([1,6,11,58,],[4,9,-2,59,]),'SEMICOLON':([8,10,26,38,48,50,51,52,54,57,61,],[11,42,-6,47,56,-21,-9,-20,-10,-8,-7,]),'COLOR':([9,47,59,],[20,20,20,]),'IMAGE':([9,47,59,],[21,21,21,]),'NUMERICVALUE':([44,49,],[50,50,]),'SOURCE':([9,47,59,],[22,22,22,]),'RB':([7,40,47,55,56,60,],[10,48,-4,-5,-3,61,]),'UNDERLINE':([9,47,59,],[24,24,24,]),'$end':([3,42,],[0,-1,]),'BODY':([4,],[6,]),'STYLE':([9,47,59,],[25,25,25,]),'BOLD':([9,47,59,],[19,19,19,]),'HEIGHT':([9,47,59,],[27,27,27,]),'PARAGRAPH':([9,47,59,],[28,28,28,]),'IMAGEATTR':([9,47,59,],[29,29,29,]),'STRINGVALUE':([5,44,49,],[8,52,52,]),'EQ':([2,13,14,15,18,19,20,22,24,27,31,35,39,41,43,],[5,-29,-25,-26,-32,-33,-30,-28,-34,-27,44,46,-35,-31,49,]),'ID':([12,16,17,21,23,28,33,34,36,37,45,],[-11,-18,-14,-19,43,-17,-12,-13,-16,-15,53,]),'LP':([25,29,30,32,],[-22,-24,-23,45,]),'H2':([9,47,59,],[33,33,33,]),'H3':([9,47,59,],[34,34,34,]),'H1':([9,47,59,],[12,12,12,]),'H6':([9,47,59,],[36,36,36,]),'H4':([9,47,59,],[17,17,17,]),'H5':([9,47,59,],[37,37,37,]),'ITALIC':([9,47,59,],[39,39,39,]),'ALIGNMENT':([9,47,59,],[41,41,41,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'attrtype':([9,47,59,],[31,31,31,]),'attr':([9,47,59,],[32,32,32,]),'title':([0,],[1,]),'assignment':([9,47,59,],[26,26,26,]),'styleattrtype':([9,47,59,],[35,35,35,]),'value':([44,49,],[51,57,]),'start':([0,],[3,]),'program':([4,],[7,]),'statement':([9,47,59,],[38,38,38,]),'statement_list':([9,47,59,],[40,55,60,]),'type':([9,47,59,],[23,23,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> title LB program RB SEMICOLON','start',5,'p_start','myParse.py',18),
  ('title -> TITLE EQ STRINGVALUE SEMICOLON','title',4,'p_title','myParse.py',23),
  ('program -> BODY LB statement_list RB SEMICOLON','program',5,'p_program','myParse.py',30),
  ('statement_list -> statement SEMICOLON','statement_list',2,'p_statement_list','myParse.py',36),
  ('statement_list -> statement SEMICOLON statement_list','statement_list',3,'p_statement_list','myParse.py',37),
  ('statement -> assignment','statement',1,'p_statement','myParse.py',45),
  ('statement -> attr LP ID RP LB statement_list RB','statement',7,'p_statement','myParse.py',46),
  ('assignment -> type ID EQ value','assignment',4,'p_assignment','myParse.py',53),
  ('assignment -> attrtype EQ value','assignment',3,'p_assignment','myParse.py',54),
  ('assignment -> styleattrtype EQ CONSTANTVALUE','assignment',3,'p_assignment','myParse.py',55),
  ('type -> H1','type',1,'p_type','myParse.py',65),
  ('type -> H2','type',1,'p_type','myParse.py',66),
  ('type -> H3','type',1,'p_type','myParse.py',67),
  ('type -> H4','type',1,'p_type','myParse.py',68),
  ('type -> H5','type',1,'p_type','myParse.py',69),
  ('type -> H6','type',1,'p_type','myParse.py',70),
  ('type -> PARAGRAPH','type',1,'p_type','myParse.py',71),
  ('type -> LINK','type',1,'p_type','myParse.py',72),
  ('type -> IMAGE','type',1,'p_type','myParse.py',73),
  ('value -> STRINGVALUE','value',1,'p_value','myParse.py',77),
  ('value -> NUMERICVALUE','value',1,'p_value','myParse.py',78),
  ('attr -> STYLE','attr',1,'p_attr','myParse.py',82),
  ('attr -> LINKATTR','attr',1,'p_attr','myParse.py',83),
  ('attr -> IMAGEATTR','attr',1,'p_attr','myParse.py',84),
  ('attrtype -> DESTINATION','attrtype',1,'p_attrtype','myParse.py',88),
  ('attrtype -> WIDTH','attrtype',1,'p_attrtype','myParse.py',89),
  ('attrtype -> HEIGHT','attrtype',1,'p_attrtype','myParse.py',90),
  ('attrtype -> SOURCE','attrtype',1,'p_attrtype','myParse.py',91),
  ('attrtype -> TEXT','attrtype',1,'p_attrtype','myParse.py',92),
  ('styleattrtype -> COLOR','styleattrtype',1,'p_styleattrtype','myParse.py',96),
  ('styleattrtype -> ALIGNMENT','styleattrtype',1,'p_styleattrtype','myParse.py',97),
  ('styleattrtype -> FONT','styleattrtype',1,'p_styleattrtype','myParse.py',98),
  ('styleattrtype -> BOLD','styleattrtype',1,'p_styleattrtype','myParse.py',99),
  ('styleattrtype -> UNDERLINE','styleattrtype',1,'p_styleattrtype','myParse.py',100),
  ('styleattrtype -> ITALIC','styleattrtype',1,'p_styleattrtype','myParse.py',101),
]
